# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


SET(CPACK_BINARY_BUNDLE "")
SET(CPACK_BINARY_CYGWIN "")
SET(CPACK_BINARY_DEB "")
SET(CPACK_BINARY_DRAGNDROP "")
SET(CPACK_BINARY_NSIS "")
SET(CPACK_BINARY_OSXX11 "")
SET(CPACK_BINARY_PACKAGEMAKER "")
SET(CPACK_BINARY_RPM "")
SET(CPACK_BINARY_STGZ "")
SET(CPACK_BINARY_TBZ2 "")
SET(CPACK_BINARY_TGZ "")
SET(CPACK_BINARY_TZ "")
SET(CPACK_BINARY_WIX "")
SET(CPACK_BINARY_ZIP "")
SET(CPACK_CMAKE_GENERATOR "Unix Makefiles")
SET(CPACK_COMPONENTS_ALL "")
SET(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
SET(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
SET(CPACK_GENERATOR "TGZ")
SET(CPACK_IGNORE_FILES "rpm-build;_CPack_Packages;\\.rpm;\\.git;\\.o;coverage_results;log;CMakeFiles;CMakeCache.txt;\\.tar\\.gz")
SET(CPACK_INSTALLED_DIRECTORIES "/home/oculus/trading-desk-project/code;/")
SET(CPACK_INSTALL_CMAKE_PROJECTS "")
SET(CPACK_INSTALL_PREFIX "/usr/local")
SET(CPACK_MODULE_PATH "/home/oculus/trading-desk-project/code/cmake")
SET(CPACK_NSIS_DISPLAY_NAME "VRTradingDesk 1.0.0")
SET(CPACK_NSIS_INSTALLER_ICON_CODE "")
SET(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
SET(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES")
SET(CPACK_NSIS_PACKAGE_NAME "VRTradingDesk 1.0.0")
SET(CPACK_OUTPUT_CONFIG_FILE "/home/oculus/trading-desk-project/code/CPackConfig.cmake")
SET(CPACK_PACKAGE_DEFAULT_LOCATION "/")
SET(CPACK_PACKAGE_DESCRIPTION_FILE "/home/oculus/trading-desk-project/code/ReleaseNotes")
SET(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Project Description")
SET(CPACK_PACKAGE_FILE_NAME "VRTradingDesk-1.0-0-Source")
SET(CPACK_PACKAGE_GROUP "Development")
SET(CPACK_PACKAGE_INSTALL_DIRECTORY "VRTradingDesk 1.0.0")
SET(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "VRTradingDesk 1.0.0")
SET(CPACK_PACKAGE_LICENSE "© 2012")
SET(CPACK_PACKAGE_NAME "VRTradingDesk")
SET(CPACK_PACKAGE_RELOCATABLE "true")
SET(CPACK_PACKAGE_VENDOR "Vendor")
SET(CPACK_PACKAGE_VERSION "1.0.0")
SET(CPACK_PACKAGE_VERSION_MAJOR "1")
SET(CPACK_PACKAGE_VERSION_MINOR "0")
SET(CPACK_PACKAGE_VERSION_PATCH "0")
SET(CPACK_RESOURCE_FILE_LICENSE "/usr/share/cmake/Templates/CPack.GenericLicense.txt")
SET(CPACK_RESOURCE_FILE_README "/usr/share/cmake/Templates/CPack.GenericDescription.txt")
SET(CPACK_RESOURCE_FILE_WELCOME "/usr/share/cmake/Templates/CPack.GenericWelcome.txt")
SET(CPACK_RPM_CHANGELOG_FILE "/home/oculus/trading-desk-project/code/ChangeLog")
SET(CPACK_RPM_PACKAGE_NAME "VRTradingDesk-1.0")
SET(CPACK_RPM_POST_INSTALL_SCRIPT_FILE "/home/oculus/trading-desk-project/code/scripts/postinstall.sh")
SET(CPACK_SET_DESTDIR "OFF")
SET(CPACK_SOURCE_CYGWIN "")
SET(CPACK_SOURCE_GENERATOR "TGZ")
SET(CPACK_SOURCE_IGNORE_FILES "rpm-build;_CPack_Packages;\\.rpm;\\.git;\\.o;coverage_results;log;CMakeFiles;CMakeCache.txt;\\.tar\\.gz")
SET(CPACK_SOURCE_INSTALLED_DIRECTORIES "/home/oculus/trading-desk-project/code;/")
SET(CPACK_SOURCE_OUTPUT_CONFIG_FILE "/home/oculus/trading-desk-project/code/CPackSourceConfig.cmake")
SET(CPACK_SOURCE_PACKAGE_FILE_NAME "VRTradingDesk-1.0-0-Source")
SET(CPACK_SOURCE_TBZ2 "")
SET(CPACK_SOURCE_TGZ "")
SET(CPACK_SOURCE_TOPLEVEL_TAG "Linux-Source")
SET(CPACK_SOURCE_TZ "")
SET(CPACK_SOURCE_ZIP "")
SET(CPACK_STRIP_FILES "")
SET(CPACK_SYSTEM_NAME "Linux")
SET(CPACK_TOPLEVEL_TAG "Linux-Source")
SET(CPACK_WIX_SIZEOF_VOID_P "8")
