
MACRO(ADD_PROJECT_EXECUTABLE EXECUTABLE_NAME)

    SET(SRC "")
    foreach (value ${ARGN})
        SET(SRC ${SRC} ${value})
    endforeach (value)

    add_executable(${EXECUTABLE_NAME} ${SRC})

    # add common project libraries here:
    TARGET_LINK_LIBRARIES(${EXECUTABLE_NAME} io)
    TARGET_LINK_LIBRARIES(${EXECUTABLE_NAME} gui)
    TARGET_LINK_LIBRARIES(${EXECUTABLE_NAME} glfw)
    TARGET_LINK_LIBRARIES(${EXECUTABLE_NAME} GL)
    TARGET_LINK_LIBRARIES(${EXECUTABLE_NAME} GLEW)
    TARGET_LINK_LIBRARIES(${EXECUTABLE_NAME} GLU)
    TARGET_LINK_LIBRARIES(${EXECUTABLE_NAME} ovr)
    TARGET_LINK_LIBRARIES(${EXECUTABLE_NAME} X11)
    TARGET_LINK_LIBRARIES(${EXECUTABLE_NAME} pthread)
    TARGET_LINK_LIBRARIES(${EXECUTABLE_NAME} Xinerama)

ENDMACRO(ADD_PROJECT_EXECUTABLE)
