
SET(CPACK_GENERATOR "TGZ")
SET(CPACK_RPM_PACKAGE_NAME ${PROJECT_PACKAGE_NAME})
SET(CPACK_SOURCE_PACKAGE_FILE_NAME  ${PROJECT_PACKAGE_NAME}-0-Source)
SET(CPACK_SOURCE_IGNORE_FILES
    "rpm-build;_CPack_Packages;\\\\.rpm;\\\\.git;\\\\.o;coverage_results;log;CMakeFiles;CMakeCache.txt;\\\\.tar\\\\.gz")
SET(CPACK_SOURCE_GENERATOR "TGZ")
SET(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Project Description")
SET(CPACK_PACKAGE_VENDOR "Vendor")
SET(CPACK_PACKAGE_LICENSE "© 2012")
SET(CPACK_PACKAGE_GROUP "Development")
SET(CPACK_RPM_CHANGELOG_FILE ${PROJECT_SOURCE_DIR}/ChangeLog)
#set(CPACK_OUTPUT_FILE_NAME "${PROJECT_PACKAGE_NAME}-0-1.fc17.x86_64.rpm")
set(CPACK_PACKAGE_FILE_NAME "${PROJECT_PACKAGE_NAME}-0")

SET(CPACK_PACKAGE_DESCRIPTION_FILE ${PROJECT_SOURCE_DIR}/ReleaseNotes)
SET(CPACK_PACKAGE_VERSION_MAJOR ${MAJOR_VERSION})
SET(CPACK_PACKAGE_VERSION_MINOR ${MINOR_VERSION})
SET(CPACK_PACKAGE_VERSION_PATCH "0")

#set(CPACK_RPM_COMPONENT_INSTALL ON)
#set(CPACK_COMPONENTS_ALL ${MAJOR_VERSION} scripts)
#SET(CPACK_RPM_COMPONENT_${MAJOR_VERSION}_REQUIRES mysql libpcap)

#SET(CPACK_RPM_PACKAGE_REQUIRES)
SET(CPACK_RPM_POST_INSTALL_SCRIPT_FILE ${PROJECT_SOURCE_DIR}/scripts/postinstall.sh)

#SET(CPACK_RPM_SPEC_MORE_DEFINE

#SET(CPACK_PACKAGE_INSTALL_DIRECTORY "CMake ${CMake_VERSION_MAJOR}.${CMake_VERSION_MINOR}")

#SET(CPACK_PACKAGE_EXECUTABLES "Colibri" "Colibri")
#SET(CPACK_PACKAGE_EXECUTABLES "ColibriLogSet" "ColibriLogSet")
INCLUDE(CPack)
