set(MAJOR_VERSION 1) 
set(MINOR_VERSION 0) 
set(VERSION_STRING "${MAJOR_VERSION}.${MINOR_VERSION}")
set(PROJECT_VERSION "${MAJOR_VERSION}.${MINOR_VERSION}")

message(STATUS "Project Version        : ${PROJECT_VERSION}")
message(STATUS "Project Version String : ${VERSION_STRING}")
set(PROJECT_PACKAGE_NAME ${CMAKE_PROJECT_NAME}-${PROJECT_VERSION})
set(NAME_EXTENSION ${PROJECT_VERSION})
message(STATUS "Project Package Name          : ${PROJECT_PACKAGE_NAME}")
message(STATUS "Project Name Extension        : ${NAME_EXTENSION}")

MARK_AS_ADVANCED(PROJECT_VERSION VERSION_STRING NAME_EXTENSION PROJECT_PACKAGE_NAME)
